---
- hosts: all
  connection: local
  tasks:
      - shell: rm saurabh.txt
        register: task_result
        until: task_result.rc == 0
        retries: 30
        delay: 2
        ignore_errors: yes
