---
- hosts: localhost
  gather_facts: no

  tasks:
 
    - name: run this command and ignore the result
      shell: ping -c 1 8.8.8.8
      register: pingout
    - debug: msg="{{ pingout.stderr }}"


