---
- hosts: all
  become: true

  vars:
    env: dev

  tasks:

  - set_fact:
     versions: "/usr/local/web/sites/helium-dev/docs/versions"
    when: {{env}} == "dev"

  - set_fact:
     versions: "/usr/local/web/sites/helium-dev/docs/versions"
    when: {{env}} == "bau"


  - set_fact:
     versions: "/usr/local/web/sites/helium-dev/docs/versions"
    when: {{env}} == "uat"

  - set_fact:
     versions: "/usr/local/web/sites/helium-dev/docs/versions"
    when: {{env}} == "prod"

