---
- hosts: localhost
  tasks:
    - name: "Checking when"
      include: 741.yml
      when:
       - ansible_distribution == "RedHat"
       - ansible_distribution_major_version == "7"
       - ansible_distribution_version == "7.4"
           
 
