---
- hosts: localhost
  remote_user: root
  sudo: yes
  pre_tasks:
     - shell: echo 'I":" Beginning to configure web server..'

  tasks:
     - include: 562.yml

  post_tasks:
     - shell: echo 'I":" Done configuring nginx web server...'

