---
- hosts: localhost
  gather_facts: no
  tasks:
      - set_fact:
          xxx: Saurabh
                  
      - debug: var=xxx
      - debug: msg="{{ xxx }} "

      - include: "bar.yml"
        vars:
          yyy: "{{ xxx }}"

